version: "3.9"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "otus-db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5430:5430"
